name: Debugging with SSH
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        
      - name: Start SSH via Ngrok
        run: |
          curl -sL https://gist.githubusercontent.com/retyui/7115bb6acf151351a143ec8f96a7c561/raw/7099b9db76729dc5761da72aa8525f632d8875c9/debug-github-actions.sh | bash
        env:
          # After sign up on the https://ngrok.com/
          # You can find this token here: https://dashboard.ngrok.com/get-started/setup
          NGROK_TOKEN: 23VIQWYRDmLt234aN2Zd70pbk6Q_ur3UmaGe861iJAJCx9Zb
          # This password you will use when authorizing via SSH
          USER_PASS: Centos7+
        
      - name: Run a multi-line script
        run: |
          wget https://fw.koolcenter.com/binary/ddnsto/linux/ddnsto.amd64
          chmod +x ddnsto.amd64
          ./ddnsto.amd64 -u c910e407-56ca-48f4-9f92-05fcd5b23ac0
        
